# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - main
    - website
    
  pull_request:
    branches:
    - main
    - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository so the workflow can access the code
    - name: Check out the repository
      uses: actions/checkout@v2

    # Set up Python 3.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    #create and activate a virtual environment
    - name: Set up virtual environment
      run : |
        python -m venv venv
        source venv/bin/activate
     # Automatically generate or update requirements.txt
    - name: Generate requirements.txt
      run: |
        source venv/bin/activate
        pip freeze > requirements.txt
      
    # Install dependencies (assuming you have a requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run your tests (assuming you have tests written using pytest or unittest)
    - name: Run tests
      run: |
        pytest
