# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for all branches
  push:
    branches: 
      - '**'
    
  pull_request:
    branches:
      - '**'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository so the workflow can access the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'  # You can specify the exact version you're using

      # Install system dependencies (like libxml2 for lxml)
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt-dev gcc

      # Create and activate a virtual environment and install dependencies in the same step
      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your tests (use pytest or whichever test framework you're using)
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
